###
GET http://localhost:8000/logs/{{message}}

###
GET http://localhost:8000/push-invoice/{{invoice_id}}

###
GET http://localhost:8000/v1/invoices

###
GET http://localhost:8000/v2/invoices

###
GET http://localhost:8000/v3/invoices